INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Accion');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Lucha');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Disparos');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Plataforma');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Musica');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Simulacion de combate');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Estrategia');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Simulacion de vida');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Arcade');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Deporte');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Puzle');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Aventura');
INSERT INTO `market`.`categorias` (`nombre`) VALUES ('Rol');